export const REFRESH_TOKEN_REPOSITORY_TOKEN = Symbol('REFRESH_TOKEN_REPOSITORY');
export const SESSION_REPOSITORY_TOKEN = Symbol('SESSION_REPOSITORY');
export const PASSWORD_RESET_TOKEN_REPOSITORY_TOKEN = Symbol(
  'PASSWORD_RESET_TOKEN_REPOSITORY',
);
export const EMAIL_VERIFICATION_TOKEN_REPOSITORY_TOKEN = Symbol(
  'EMAIL_VERIFICATION_TOKEN_REPOSITORY',
);
