export enum ImageEntityType {
  MASTER_SERVICE = 'MASTER_SERVICE',
  MASTER_PROFILE_AVATAR = 'MASTER_PROFILE_AVATAR',
  CLIENT_PROFILE_AVATAR = 'CLIENT_PROFILE_AVATAR',
  BUG_REPORT = 'BUG_REPORT',
}
