export enum EAppointmentChatMessageActor {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
  SUPPORT = 'SUPPORT',
}

export enum EAppointmentChatSystemAction {
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
}
