export enum EAppointmentChatMessageActor {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
  SUPPORT = 'SUPPORT',
}

export enum EAppointmentChatSystemAction {
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
}

export enum EAppointmentChatMessageDeleteMode {
  FOR_EVERYONE = 'FOR_EVERYONE',
  FOR_ME = 'FOR_ME',
}

export enum EAppointmentChatMessageReplyPreviewStatus {
  AVAILABLE = 'AVAILABLE',
  DELETED = 'DELETED',
}
