export const FILTER_ENUM_ARRAY_MAX_ITEMS = 50;
export const FILTER_STRING_ARRAY_MAX_ITEMS = 50;
export const FILTER_UUID_ARRAY_MAX_ITEMS = 200;
export const FILTER_STRING_ITEM_MAX_LENGTH = 256;
export const FILTER_TEXT_SEARCH_MAX_LENGTH = 500;
