-- AlterEnum
ALTER TYPE "ImageEntityType" ADD VALUE 'MASTER_PROFILE_BANNER';
ALTER TYPE "ImageEntityType" ADD VALUE 'CLIENT_PROFILE_BANNER';

-- AlterEnum
ALTER TYPE "FilePurpose" ADD VALUE 'MASTER_PROFILE_BANNER';
ALTER TYPE "FilePurpose" ADD VALUE 'PROFILE_BANNER';
