export enum NotificationCategory {
  APPOINTMENT = 'APPOINTMENT',
  CHAT = 'CHAT',
  REVIEW = 'REVIEW',
  SYSTEM = 'SYSTEM',
}

export enum NotificationType {
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  REVIEW_CREATED = 'REVIEW_CREATED',
  REVIEW_REACTION = 'REVIEW_REACTION',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  SYSTEM_SECURITY = 'SYSTEM_SECURITY',
}

export enum NotificationRelatedEntityType {
  APPOINTMENT = 'APPOINTMENT',
  APPOINTMENT_CHAT = 'APPOINTMENT_CHAT',
  APPOINTMENT_CHAT_MESSAGE = 'APPOINTMENT_CHAT_MESSAGE',
  MASTER_SERVICE_REVIEW = 'MASTER_SERVICE_REVIEW',
  MASTER_PROFILE = 'MASTER_PROFILE',
  USER = 'USER',
}
